cmake_minimum_required(VERSION 3.24)

if(NOT DEFINED SOURCE_DIR OR NOT IS_DIRECTORY "${SOURCE_DIR}")
    message(FATAL_ERROR "AssertLayers.cmake needs a valid SOURCE_DIR")
endif()

set(LAYERS reflect platform lua scene serial components physics gfx/vk gfx/asset gfx/pass gfx script core dev player editor)
set(ALLOWED_reflect platform)
set(ALLOWED_platform "")
set(ALLOWED_lua platform)
set(ALLOWED_scene reflect platform)
set(ALLOWED_serial scene reflect platform)
set(ALLOWED_components scene reflect platform)
set(ALLOWED_physics scene reflect lua platform)
set(ALLOWED_gfx/vk platform)
set(ALLOWED_gfx/asset gfx/vk scene platform)
set(ALLOWED_gfx/pass gfx/asset gfx/vk scene lua platform)
set(ALLOWED_gfx gfx/pass gfx/asset gfx/vk scene lua platform)
set(ALLOWED_script scene reflect gfx physics platform lua)
set(ALLOWED_core reflect platform lua scene serial components physics gfx/vk gfx/asset gfx/pass gfx script)
set(ALLOWED_dev ${ALLOWED_core} core)
set(ALLOWED_player core platform)
set(ALLOWED_editor core dev platform)

function(layer_of path output)
    if(path MATCHES "^(gfx/(vk|asset|pass))/")
        set(${output} "${CMAKE_MATCH_1}" PARENT_SCOPE)
    elseif(path MATCHES "^([^/]+)/")
        set(${output} "${CMAKE_MATCH_1}" PARENT_SCOPE)
    else()
        set(${output} "" PARENT_SCOPE)
    endif()
endfunction()

file(GLOB_RECURSE SOURCES RELATIVE "${SOURCE_DIR}" "${SOURCE_DIR}/*.cpp" "${SOURCE_DIR}/*.hpp")
foreach(SOURCE IN LISTS SOURCES)
    layer_of("${SOURCE}" LAYER)
    if(NOT LAYER IN_LIST LAYERS)
        message(FATAL_ERROR "Unknown source layer: ${SOURCE}")
    endif()

    file(READ "${SOURCE_DIR}/${SOURCE}" CONTENT)
    string(REGEX REPLACE "#[ \t]*include[ \t]+\"dev/[^\"]+\"" "" CONTENT "${CONTENT}")
    if(NOT LAYER STREQUAL "dev" AND CONTENT MATCHES "ImGui|ImDraw|ImVec[24]|IMGUI_|imgui")
        message(FATAL_ERROR "Editor-only ImGui reference in ${SOURCE}")
    endif()

    file(STRINGS "${SOURCE_DIR}/${SOURCE}" INCLUDES REGEX "^[ \t]*#[ \t]*include[ \t]+[\"<]")
    foreach(INCLUDE IN LISTS INCLUDES)
        string(REGEX REPLACE "^[ \t]*#[ \t]*include[ \t]+[\"<]([^\">]+)[\">].*$" "\\1" HEADER "${INCLUDE}")
        if(HEADER MATCHES "(^|/)\\.\\.?/")
            message(FATAL_ERROR "Include must use the src root: ${SOURCE} -> ${HEADER}")
        endif()
        layer_of("${HEADER}" DEPENDENCY)
        if(NOT DEPENDENCY IN_LIST LAYERS OR DEPENDENCY STREQUAL LAYER)
            continue()
        endif()
        if(NOT DEPENDENCY IN_LIST ALLOWED_${LAYER})
            message(FATAL_ERROR "Forbidden layer dependency: ${SOURCE} -> ${HEADER}")
        endif()
    endforeach()
endforeach()
