cmake_minimum_required(VERSION 3.24)

function(check_case name source content expected)
    set(ROOT "${BINARY_DIR}/layer-checks/${name}")
    get_filename_component(DIRECTORY "${ROOT}/${source}" DIRECTORY)
    file(MAKE_DIRECTORY "${DIRECTORY}")
    file(WRITE "${ROOT}/${source}" "${content}")
    execute_process(COMMAND "${CMAKE_COMMAND}" "-DSOURCE_DIR=${ROOT}" -P "${CHECKER}"
        RESULT_VARIABLE RESULT OUTPUT_VARIABLE OUTPUT ERROR_VARIABLE ERROR)
    if(expected AND NOT RESULT EQUAL 0)
        message(FATAL_ERROR "${name} unexpectedly failed: ${OUTPUT}${ERROR}")
    elseif(NOT expected AND RESULT EQUAL 0)
        message(FATAL_ERROR "${name} unexpectedly passed")
    endif()
endfunction()

check_case(allowed core/Example.cpp "#include \"scene/Scene.hpp\"\n#include <vector>\n" TRUE)
check_case(editor dev/Example.cpp "#include <imgui.h>\nImGui::Begin(\"Test\");\n" TRUE)
check_case(editor_entry editor/Example.cpp "#include \"dev/ImGuiLayer.hpp\"\n" TRUE)
check_case(upward scene/Example.cpp "#include \"core/Engine.hpp\"\n" FALSE)
check_case(renderer_parent gfx/vk/Example.cpp "#include \"gfx/Renderer.hpp\"\n" FALSE)
check_case(runtime_editor core/Example.cpp "#include \"dev/History.hpp\"\n" FALSE)
check_case(imgui_include core/Example.cpp "#include <imgui.h>\n" FALSE)
check_case(imgui_symbol gfx/Example.cpp "ImGui::Begin(\"Test\");\n" FALSE)
check_case(imgui_type gfx/Example.cpp "ImGuiContext* context;\n" FALSE)
check_case(relative scene/Example.cpp "#include \"../core/Engine.hpp\"\n" FALSE)
check_case(unknown unknown/Example.cpp "#include <vector>\n" FALSE)
