cmake_minimum_required(VERSION 3.24)

function(check_case name source content expected)
    set(ROOT "${BINARY_DIR}/layer-checks/${name}")
    file(REMOVE_RECURSE "${ROOT}")
    get_filename_component(DIRECTORY "${ROOT}/${source}" DIRECTORY)
    file(MAKE_DIRECTORY "${DIRECTORY}")
    file(WRITE "${ROOT}/${source}" "${content}")
    execute_process(COMMAND "${CMAKE_COMMAND}" "-DSOURCE_DIR=${ROOT}" -P "${CHECKER}"
        RESULT_VARIABLE RESULT OUTPUT_VARIABLE OUTPUT ERROR_VARIABLE ERROR)
    if(expected AND NOT RESULT EQUAL 0)
        message(FATAL_ERROR "${name} unexpectedly failed: ${OUTPUT}${ERROR}")
    elseif(NOT expected AND RESULT EQUAL 0)
        message(FATAL_ERROR "${name} unexpectedly passed")
    endif()
endfunction()

check_case(allowed core/Example.cpp "#include \"scene/Scene.hpp\"\n#include <vector>\n" TRUE)
check_case(ui_up ui/core/Example.cpp "#include \"scene/Scene.hpp\"\n" FALSE)
check_case(ui_down ui/widgets/Example.cpp "#include \"ui/core/Widget.hpp\"\n#include \"text/Font.hpp\"\n" TRUE)
check_case(ui_sideways ui/core/Example.cpp "#include \"ui/widgets/Button.hpp\"\n" FALSE)
check_case(ui_flat ui/Example.cpp "#include <vector>\n" FALSE)
check_case(renderer_ui gfx/Example.cpp "#include \"ui/core/ElementList.hpp\"\n" TRUE)
check_case(renderer_widgets gfx/Example.cpp "#include \"ui/widgets/Button.hpp\"\n" FALSE)
check_case(text_leaf text/Example.cpp "#include \"gfx/Renderer.hpp\"\n" FALSE)
check_case(upward scene/Example.cpp "#include \"core/Engine.hpp\"\n" FALSE)
check_case(renderer_parent gfx/vk/Example.cpp "#include \"gfx/Renderer.hpp\"\n" FALSE)
check_case(runtime_editor core/Example.cpp "#include \"dev/History.hpp\"\n" FALSE)
check_case(relative scene/Example.cpp "#include \"../core/Engine.hpp\"\n" FALSE)
check_case(rhi_is_a_leaf gfx/rhi/Example.cpp "#include \"gfx/vk/VkCtx.hpp\"\n" FALSE)
check_case(rhi_no_scene gfx/rhi/Example.cpp "#include \"scene/Scene.hpp\"\n" FALSE)
check_case(backend_on_rhi gfx/vk/Example.cpp "#include \"gfx/rhi/Handles.hpp\"\n" TRUE)
check_case(pass_on_rhi gfx/pass/Example.cpp "#include \"gfx/rhi/Commands.hpp\"\n" TRUE)
check_case(backend_leak_gfx gfx/Example.cpp "#include \"gfx/vk/Ctx.hpp\"\n" FALSE)
check_case(backend_leak_pass gfx/pass/Example.cpp "#include \"gfx/vk/Ctx.hpp\"\n" FALSE)
check_case(backend_leak_asset gfx/asset/Example.cpp "#include \"gfx/vk/Ctx.hpp\"\n" FALSE)
check_case(backend_leak_core core/Example.cpp "#include \"gfx/vk/Ctx.hpp\"\n" FALSE)
check_case(backends_are_blind gfx/mtl/Example.cpp "#include \"gfx/vk/Ctx.hpp\"\n" FALSE)
check_case(metal_on_rhi gfx/mtl/Example.cpp "#include \"gfx/rhi/Handles.hpp\"\n" TRUE)
check_case(unknown unknown/Example.cpp "#include <vector>\n" FALSE)
